import type { AppointmentMeetingCopy } from "@/components/appointment-meeting";
import type { AppointmentStatus } from "@/lib/appointment-agenda";

export type AppointmentsCopy = {
  meeting: AppointmentMeetingCopy;
  statuses: Record<AppointmentStatus, string>;
  upcoming: string;
  past: string;
  views: string;
  today: string;
  tomorrow: string;
  timeZone: string;
  loading: string;
  reschedule: string;
  cancel: string;
  notice: string;
  locked: string;
  pendingBody: string;
  pendingMeeting: string;
  upcomingEmpty: string;
  upcomingEmptyBody: string;
  pastEmpty: string;
  pastEmptyBody: string;
  loadError: string;
  retry: string;
  loadMore: string;
  rescheduleTitle: string;
  rescheduleBody: string;
  cancelTitle: string;
  cancelBody: string;
  noTimes: string;
  timesError: string;
  nextTimes: string;
  previousTimes: string;
  morning: string;
  afternoon: string;
  evening: string;
  save: string;
  saving: string;
  confirmCancel: string;
  back: string;
  saveError: string;
  noticeError: string;
  changedError: string;
  weeklyReschedulePolicy: string;
  rescheduleLimitReached: string;
  reschedulingDisabled: string;
  rescheduleLimitError: string;
  rescheduleSuccess: string;
  cancelSuccess: string;
};
